const CONFIG = {
    titleWeb: "crush của Phước",
    introTitle: 'Hé luu crush',
    introDesc: `mình có điều này bạn phải nói thật lòng nha😘`,
    btnIntro: '^^Okii luôn^^',
    title: 'Bạn thích mình có phải không🥰',
    desc: 'Nếu mà bạn thoát ra thì bạn là người yêu mình đó nha😁',
    btnYes: 'Đúng rồi thích Phước đấy❤️',
    btnNo: 'Không có chuyện đó đâu :3',
    question: 'Lí do bạn thích mình là gì thế❤️',
    btnReply: 'Gửi cho bạn <3',
    reply: 'Tại vì thích là thích chẳng cần lí do',
    mess: 'Mình biết mà 🥰. iuiu nhìu 😘😘',
    messDesc: 'Vậy quay ra bật chế độ hẹn hò nào😘.',
    btnAccept: 'Okiiiii lun <3',
    messLink: 'https://www.facebook.com/phuocpho00
